# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Plugins
plugins: 		      [jekyll-paginate, jekyll-gist]


# Setup
title:            'Yihang Yin'
tagline:          'Somedaywilldo'
description:	    'Michael<br>Somedaywilldo<br><br>School of Computer Science and Engineering<br>Beihang University<br><br>Exchange Student at Applied Science and Engineering<br>University of Toronto'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://somedaywilldo.github.io/
baseurl:          https://somedaywilldo.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0
github:           https://github.com/Somedaywilldo/
# email:            yihangmichael [dot] yin [at] gmail [dot] com
